name: CI/CD to EC2

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
          docker save myapp:latest > myapp.tar

      - name: Copy Docker image to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ec2-3-38-179-12.ap-northeast-2.compute.amazonaws.com
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key myapp.tar ${USER}@${HOST}:~/ 
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            docker load < myapp.tar
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:8080 myapp:latest
          '
          rm -f private_key
