name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      run: |
        docker build -t myapp:latest .
        docker save myapp:latest > myapp.tar

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.AWS_EC2_HOST }}
        USER: ${{ secrets.AWS_EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -o StrictHostKeyChecking=no -i private_key myapp.tar ${USER}@${HOST}:~/
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          sudo docker load < myapp.tar
          sudo docker stop myapp || true
          sudo docker rm myapp || true
          sudo docker run --add-host host.docker.internal:host-gateway -d --name myapp -p 8080:8080 myapp:latest
        '

    - name: Clean up
      run: rm -f private_key
